//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS_Drinks_API.soapservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drink", Namespace="soapservice")]
    [System.SerializableAttribute()]
    public partial class Drink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="soapservice", ConfigurationName="soapservice.GetDataSoap")]
    public interface GetDataSoap {
        
        // CODEGEN: Generating message contract since element name val from namespace soapservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="soapservice/GetDrink", ReplyAction="*")]
        IIS_Drinks_API.soapservice.GetDrinkResponse GetDrink(IIS_Drinks_API.soapservice.GetDrinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="soapservice/GetDrink", ReplyAction="*")]
        System.Threading.Tasks.Task<IIS_Drinks_API.soapservice.GetDrinkResponse> GetDrinkAsync(IIS_Drinks_API.soapservice.GetDrinkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrink", Namespace="soapservice", Order=0)]
        public IIS_Drinks_API.soapservice.GetDrinkRequestBody Body;
        
        public GetDrinkRequest() {
        }
        
        public GetDrinkRequest(IIS_Drinks_API.soapservice.GetDrinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="soapservice")]
    public partial class GetDrinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string val;
        
        public GetDrinkRequestBody() {
        }
        
        public GetDrinkRequestBody(string val) {
            this.val = val;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrinkResponse", Namespace="soapservice", Order=0)]
        public IIS_Drinks_API.soapservice.GetDrinkResponseBody Body;
        
        public GetDrinkResponse() {
        }
        
        public GetDrinkResponse(IIS_Drinks_API.soapservice.GetDrinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="soapservice")]
    public partial class GetDrinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IIS_Drinks_API.soapservice.Drink GetDrinkResult;
        
        public GetDrinkResponseBody() {
        }
        
        public GetDrinkResponseBody(IIS_Drinks_API.soapservice.Drink GetDrinkResult) {
            this.GetDrinkResult = GetDrinkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetDataSoapChannel : IIS_Drinks_API.soapservice.GetDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataSoapClient : System.ServiceModel.ClientBase<IIS_Drinks_API.soapservice.GetDataSoap>, IIS_Drinks_API.soapservice.GetDataSoap {
        
        public GetDataSoapClient() {
        }
        
        public GetDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IIS_Drinks_API.soapservice.GetDrinkResponse IIS_Drinks_API.soapservice.GetDataSoap.GetDrink(IIS_Drinks_API.soapservice.GetDrinkRequest request) {
            return base.Channel.GetDrink(request);
        }
        
        public IIS_Drinks_API.soapservice.Drink GetDrink(string val) {
            IIS_Drinks_API.soapservice.GetDrinkRequest inValue = new IIS_Drinks_API.soapservice.GetDrinkRequest();
            inValue.Body = new IIS_Drinks_API.soapservice.GetDrinkRequestBody();
            inValue.Body.val = val;
            IIS_Drinks_API.soapservice.GetDrinkResponse retVal = ((IIS_Drinks_API.soapservice.GetDataSoap)(this)).GetDrink(inValue);
            return retVal.Body.GetDrinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IIS_Drinks_API.soapservice.GetDrinkResponse> IIS_Drinks_API.soapservice.GetDataSoap.GetDrinkAsync(IIS_Drinks_API.soapservice.GetDrinkRequest request) {
            return base.Channel.GetDrinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<IIS_Drinks_API.soapservice.GetDrinkResponse> GetDrinkAsync(string val) {
            IIS_Drinks_API.soapservice.GetDrinkRequest inValue = new IIS_Drinks_API.soapservice.GetDrinkRequest();
            inValue.Body = new IIS_Drinks_API.soapservice.GetDrinkRequestBody();
            inValue.Body.val = val;
            return ((IIS_Drinks_API.soapservice.GetDataSoap)(this)).GetDrinkAsync(inValue);
        }
    }
}
